name: Ticket Number Check

on:
  pull_request:
    types: [opened, edited]

jobs:
  check-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR for ticket number
        run: |
          echo "PR Title: Update Readme.txt"
          echo "PR Body: TICKET-123"

          if [[ ! "Update Readme.txt" =~ TICKET-[0-9]+ ]] && [[ ! "TICKET-123" =~ TICKET-[0-9]+ ]]; then
            echo "Error: No ticket number found in the PR title or description."
            exit 1
          else
            echo "Ticket number found. PR is valid."
          fi
